version: '3.8'
services:
  database:
    image: postgres:alpine3.18
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=schema_book
    ports:
      - "5432:5432"