spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/schema_book

  jpa:
    show-sql: true
    generate-ddl: true

    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true
        show_sql: true

flyway:
  schemas: schema_book
  baselineOnMigrate: true
  enabled: true

clients:
  open-library:
    base-url: https://openlibrary.org

sqs:
  book-synchronization-queue: book-queue

cloud:
  aws:
    region:
      static: us-east-1
    credentials:
      access-key: ak
      secret-key: sk
    end-point:
      uri: https://sqs.us-east-1.amazonaws.com/cn/book-queue
    stack:
      auto: false