
spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres

  jpa:
    show-sql: true
    generate-ddl: true

#    hibernate:
#      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true
        show_sql: true

  flyway:
    default-schema: postgres
    create-schemas: true
    schemas: postgres
    baseline-on-migrate: true
    enabled: true
