aws:
  account: 000000

spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/schema_book

  cloud:
    aws:
      endpoint: https://sqs.us-east-1.amazonaws.com/${aws.account}/mbook-queue
      region:
        static: us-east-1

  jpa:
    show-sql: true
    generate-ddl: true

    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true
        show_sql: true

flyway:
  schemas: schema_book
  baselineOnMigrate: true
  enabled: true

clients:
  open-library:
    base-url: https://openlibrary.org

sqs:
  book-synchronization-queue: mbook-queue

server:
  error:
    include-message: always